### PR TITLE
Add PC_Projective

### PR DESCRIPTION
**Pull request by elemoine**
This is still WIP. DO NOT MERGE JUST NOW.

### CODE REVIEW

**Comment by mbredif** [comment]
Great !
Apart for the missing tests here are my comments that apply more generally to all transforms (subject to discussion obviously)
- transforms should maybe return pc_true/pc_false to indicate transformation failure. Maybe we should return silently null pcpoints upon failure and return only the successfully transformed pcpoints in transformed pcpatches(not sure what postgis does for st_transform). Transformation failures will not be so exceptionnal in proj4.and distorsion transforms
- xyzdimnames could now default to the x y z positions (which have just been merged upstream)
- there is a lot of replicated code among transformations... maybe the tag-based approach of pc_filter could be reused here.
(- 16 float is a looooooong argument list....)

Good work !

**Comment by elemoine** [comment]
> - 16 float is a looooooong argument list.

Yes, do you have suggestions for that?

**Comment by mbredif** [comment]
We could pass around a PCMAT44 internally after constructing it in the pgsql wrapping code.
The sql transformation signatures is not relying on an array of floats to align with postgis transforms.
In LI3DS, we have to discuss with @ldgeo how the parameters of transforms and transform stacks will be passed (jsonb? New PCTRANSFORM type? ...)

**Comment by elemoine** [comment]
> xyzdimnames could now default to the x y z positions (which have just been merged upstream)

See https://github.com/LI3DS/pointcloud/pull/57 for this.

**Comment by elemoine** [comment]
> We could pass around a PCMAT44 internally after constructing it in the pgsql wrapping code.

Yep, we could do that. In this way, we will only add one value to the stack when calling the internal function. Sounds like a good idea to me.

I can create a PR for that.

> The sql transformation signatures is not relying on an array of floats to align with postgis transforms.

Yep, exactly.

> In LI3DS, we have to discuss with @ldgeo how the parameters of transforms and transform stacks will be passed (jsonb? New PCTRANSFORM type? ...)

**Comment by elemoine** [comment]
> there is a lot of replicated code among transformations... maybe the tag-based approach of pc_filter could be reused here.

Could you please elaborate? I don't understand what you mean by "tag-based approach of pc_filter"… Thank you.

**Comment by mbredif** [comment]
I think you can merge this PR after rebasing and using the related bits of #60 for the PC_FAILURE/SUCCESS return values, leaving the treatment of my other more orthogonal concerns to other PRs
- #57 for default dimension names
- #?? for internally passing around PCMAT44 (or similiar) objects rather than long lists of double parameters
- #?? for pc_filter - like tag-based coding (PC_TRANSFORMTYPE enum and parameters as a double *)

**Comment by elemoine** [comment]
> I think you can merge this PR after rebasing and using the related bits of #60 for the PC_FAILURE/SUCCESS return values

Can you please be more specific? Are you really talking about #60 here?

**Comment by mbredif** [comment]
> Can you please be more specific? Are you really talking about #60 here?

Yes, I confess #60 is much too big.
I was referring to the error handling of [pc_vector_3_from_homogeneous](/LI3DS/pointcloud/blob/282f4fcb6f44c4d5987cffc5bdb991d670a33964/lib/pc_matrix.c#L259-L267) and [pc_vector_3_projective](https://github.com/LI3DS/pointcloud/blob/282f4fcb6f44c4d5987cffc5bdb991d670a33964/lib/pc_matrix.c#L380-L386)

**Comment by elemoine** [comment]
> Yes, I confess #60 is much too big.
> I was referring to the error handling of pc_vector_3_from_homogeneous and pc_vector_3_projective

Ok, got it.

**Comment by elemoine** [comment]
PR base changed from `dev` to `master`.

**Comment by elemoine** [comment]
@mbredif tests added. (I even found a bug while writing the tests.)

**Comment by mbredif** [comment]
Thanks @elemoine for your work !
Just out of curiosity, what was the bug ?

**Comment by elemoine** [comment]
`mat[16]` instead of `mat[15]` in a matrix function :)

**Pull request merged**
