### PR TITLE
Use default dimension names for the transform functions

### PR DESCRIPTION
**Pull request by elemoine**
@mbredif is this what you had in mind? Thanks.

### CODE REVIEW

**Comment by mbredif** [comment]
Yes, that is exactly the functionnality I have in mind.

Implementation-wise, upstream PR pgpointcloud/pointcloud#143 could simplify the coding by
- putting the `if(dim)` checks inside the getters and setters so that they may always be used (and do nothing if dim is null)
- `xdim = pc_schema_get_dimension_by_name(schema, xdimname);` and the likes could alternatively be replaced with `xdim = xdimname ? pc_schema_get_dimension_by_name(schema, xdimname) : schema->xdim;` and initialize the xyzm to 0 so that missing dimensions get a default 0 value if the getter fails due to a missing dimension.

as a side-note, you may still want to check that functions with named dimensions still work :) (It looks like you are only testing default dimension names now)

**Comment by elemoine** [comment]
> Implementation-wise, upstream PR pgpointcloud/pointcloud#143 could simplify the coding by

Yep. Let's make Sandro merge pgpointcloud/pointcloud#143 :) And then we can come back to our transform code and make the improvements that you suggest.

 

> as a side-note, you may still want to check that functions with named dimensions still work :) (It looks like you are only testing default dimension names now)

That's right. I can just add a specific unit test for the "non-dimensions" case. I'll add a commit to my branch for that.

**Comment by elemoine** [comment]
`with_dimension_names` tests added.

I think this is ready to be merged.

**Comment by elemoine** [comment]
@mbredif do you agree witth merging this?

**Comment by mbredif** [comment]
Sure, merged ! thanks for the good work :)

**Pull request merged**
